export default [
  {
    id: 1,
    title: "Colors",
    desc: "Choose from three bold finishes. iPhone 17 Pro shown in Deep Blue.",
    isActive: false,
    img: "orange.jpg",
  },
  {
    id: 2,
    title: "Aluminum unibody",
    desc: "Optimized for performance and battery. Aluminum alloy is remarkably light and has exceptional thermal conductivity.",
    isActive: false,
    content: { type: "video", url: "unibody.mp4", cover: "unibody.jpg" },
		img: "unibody.jpg",
  },
  {
    id: 3,
    title: "Vapor chamber",
    desc: "Deionized water sealed inside moves heat away from the A19 Pro chip, allowing for even higher sustained performance.",
    isActive: false,
    img: "vapor.jpg",
  },
  {
    id: 4,
    title: "Ceramic Shield",
    desc: "Protects the back of iPhone 17 Pro, making it 4x more resistant to cracks.4 New Ceramic Shield 2 on the front has 3x better scratch resistance.5",
    isActive: false,
    img: "ceramic.jpg",
  },
  {
    id: 5,
    title: "Immersive pro display",
    desc: "Our best‑ever 6.3‑inch and 6.9‑inch Super Retina XDR displays.6 Brighter. Better anti‑reflection. ProMotion up to 120Hz.",
    isActive: false,
    img: "display.jpg",
  },
  {
    id: 6,
    title: "Camera Control",
    desc: "Instantly take a photo, record video, adjust settings, and more. So you never miss a moment.",
    isActive: false,
    img: "camera.jpg",
  },
  {
    id: 7,
    title: "Action button",
    desc: "A customizable fast track to your favorite feature. Long press to launch the action you want — Silent mode, Translation, Shortcuts, and more.",
    isActive: false,
    img: "action.jpg",
  },
];
