import { Noto_Sans } from 'next/font/google'
import './reset.css'

import './globals.css'

const notoSans = Noto_Sans({
	variable: '--font-noto-sans',
	subsets: ['latin', 'cyrillic'],
	display: 'swap',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${notoSans.variable} center-content`}>{children}</body>
		</html>
	)
}
